### PR TITLE
FIX: moved DfaUtils and DfaLTS to a separate file

### PR DESCRIPTION
**Pull request by Kobzol**
Moved the two classes to a separate file to solve the serialization issue.
There is a separate problem that occurs with the newest version of distributed, I'll handle that later (it's working with my version but I'm not sure if it'll work with yours).

### CODE REVIEW

**Comment by Kobzol** [comment]
There is an error in the master branch of `distributed`, use the stable version (`pip install distributed`).

**Comment by msurkovsky** [comment]
Thanks for your fix. I'm going to try get rid of DfaUtils class to check whether or not it is the problem. I'm still not fully convinced about it because of very similar implementation of dpda. Maybe later we can discuss what the guides for making programs should be; imho there should be none or as few as possible.

**Comment by msurkovsky** [comment]
Ok, in my `dev/syncdfa-salomon-deploy` is a rewritten version. DfaUtils class has been removed and as far as I see the current version follow the same pattern as `dpda`. However, the error still remains the same.

**Comment by msurkovsky** [comment]
Yeahh, I've found the problem and how to change the program so it works on _Salomon_ without separating the program into two files. Moreover it works with original version with `DfaUtils` class.

**The proble is solved by:**
exchange the call `super(DfaLTS, self).__init__(actions)` for `hd.DLTS.__init__(self, actions)` in `DfaLTS` `__init__` method.

**Pull request closed without merging**
